// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/users/users.proto

package users

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PersonId                   string   `protobuf:"bytes,2,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	PersonName                 string   `protobuf:"bytes,3,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"`
	PersonInitials             string   `protobuf:"bytes,4,opt,name=person_initials,json=personInitials,proto3" json:"person_initials,omitempty"`
	OrgFunctionId              int32    `protobuf:"varint,5,opt,name=org_function_id,json=orgFunctionId,proto3" json:"org_function_id,omitempty"`
	PersonPosition             string   `protobuf:"bytes,6,opt,name=person_position,json=personPosition,proto3" json:"person_position,omitempty"`
	PersonDateRegistered       int64    `protobuf:"varint,7,opt,name=person_date_registered,json=personDateRegistered,proto3" json:"person_date_registered,omitempty"`
	PersonSubscriptionFinish   int64    `protobuf:"varint,8,opt,name=person_subscription_finish,json=personSubscriptionFinish,proto3" json:"person_subscription_finish,omitempty"`
	PersonEmail                string   `protobuf:"bytes,9,opt,name=person_email,json=personEmail,proto3" json:"person_email,omitempty"`
	PersonTelephone            string   `protobuf:"bytes,10,opt,name=person_telephone,json=personTelephone,proto3" json:"person_telephone,omitempty"`
	PersonFax                  string   `protobuf:"bytes,11,opt,name=person_fax,json=personFax,proto3" json:"person_fax,omitempty"`
	PersonAddress              string   `protobuf:"bytes,12,opt,name=person_address,json=personAddress,proto3" json:"person_address,omitempty"`
	CategoryId                 int32    `protobuf:"varint,13,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	PersonMainHiredCompany     string   `protobuf:"bytes,14,opt,name=person_main_hired_company,json=personMainHiredCompany,proto3" json:"person_main_hired_company,omitempty"`
	PersonContractorDepartment string   `protobuf:"bytes,15,opt,name=person_contractor_department,json=personContractorDepartment,proto3" json:"person_contractor_department,omitempty"`
	PersonSubcontractor        string   `protobuf:"bytes,16,opt,name=person_subcontractor,json=personSubcontractor,proto3" json:"person_subcontractor,omitempty"`
	PersonPassword             string   `protobuf:"bytes,17,opt,name=person_password,json=personPassword,proto3" json:"person_password,omitempty"`
	PersonIsOnline             int32    `protobuf:"varint,18,opt,name=person_is_online,json=personIsOnline,proto3" json:"person_is_online,omitempty"`
	IsActive                   int32    `protobuf:"varint,19,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsDeleted                  int32    `protobuf:"varint,20,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetPersonId() string {
	if m != nil {
		return m.PersonId
	}
	return ""
}

func (m *User) GetPersonName() string {
	if m != nil {
		return m.PersonName
	}
	return ""
}

func (m *User) GetPersonInitials() string {
	if m != nil {
		return m.PersonInitials
	}
	return ""
}

func (m *User) GetOrgFunctionId() int32 {
	if m != nil {
		return m.OrgFunctionId
	}
	return 0
}

func (m *User) GetPersonPosition() string {
	if m != nil {
		return m.PersonPosition
	}
	return ""
}

func (m *User) GetPersonDateRegistered() int64 {
	if m != nil {
		return m.PersonDateRegistered
	}
	return 0
}

func (m *User) GetPersonSubscriptionFinish() int64 {
	if m != nil {
		return m.PersonSubscriptionFinish
	}
	return 0
}

func (m *User) GetPersonEmail() string {
	if m != nil {
		return m.PersonEmail
	}
	return ""
}

func (m *User) GetPersonTelephone() string {
	if m != nil {
		return m.PersonTelephone
	}
	return ""
}

func (m *User) GetPersonFax() string {
	if m != nil {
		return m.PersonFax
	}
	return ""
}

func (m *User) GetPersonAddress() string {
	if m != nil {
		return m.PersonAddress
	}
	return ""
}

func (m *User) GetCategoryId() int32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *User) GetPersonMainHiredCompany() string {
	if m != nil {
		return m.PersonMainHiredCompany
	}
	return ""
}

func (m *User) GetPersonContractorDepartment() string {
	if m != nil {
		return m.PersonContractorDepartment
	}
	return ""
}

func (m *User) GetPersonSubcontractor() string {
	if m != nil {
		return m.PersonSubcontractor
	}
	return ""
}

func (m *User) GetPersonPassword() string {
	if m != nil {
		return m.PersonPassword
	}
	return ""
}

func (m *User) GetPersonIsOnline() int32 {
	if m != nil {
		return m.PersonIsOnline
	}
	return 0
}

func (m *User) GetIsActive() int32 {
	if m != nil {
		return m.IsActive
	}
	return 0
}

func (m *User) GetIsDeleted() int32 {
	if m != nil {
		return m.IsDeleted
	}
	return 0
}

type Response struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Updated              bool     `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Deleted              bool     `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	User                 *User    `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

func (m *Response) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "users.User")
	proto.RegisterType((*Response)(nil), "users.Response")
}

func init() { proto.RegisterFile("proto/users/users.proto", fileDescriptor_bb78b70ef3ad6f73) }

var fileDescriptor_bb78b70ef3ad6f73 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x6f, 0x4f, 0x53, 0x3d,
	0x14, 0x7f, 0xb6, 0x31, 0xd8, 0xce, 0x80, 0x41, 0x21, 0xcf, 0xd3, 0x07, 0x31, 0x0c, 0x12, 0x75,
	0x26, 0x06, 0x23, 0xf8, 0xc6, 0xc4, 0x18, 0x91, 0x89, 0xf2, 0x42, 0x25, 0x17, 0x79, 0x7d, 0x53,
	0x6e, 0x0f, 0xa3, 0xc9, 0xd6, 0xde, 0xb4, 0x1d, 0xc2, 0x87, 0xf0, 0x1b, 0xf8, 0x39, 0xfc, 0x7c,
	0xa6, 0xa7, 0xbd, 0x63, 0xea, 0x0b, 0x78, 0xb3, 0xe4, 0xfc, 0xfe, 0x9c, 0xb5, 0xbf, 0xd3, 0x73,
	0xe1, 0xbf, 0xd2, 0x1a, 0x6f, 0x9e, 0x4f, 0x1c, 0x5a, 0x17, 0x7f, 0x77, 0x09, 0x61, 0x4d, 0x2a,
	0x76, 0x7e, 0xce, 0xc3, 0xdc, 0x99, 0x43, 0xcb, 0x96, 0xa1, 0xae, 0x24, 0xaf, 0xf5, 0x6a, 0xfd,
	0x76, 0x56, 0x57, 0x92, 0x3d, 0x80, 0x76, 0x89, 0xd6, 0x19, 0x9d, 0x2b, 0xc9, 0xeb, 0x04, 0xb7,
	0x22, 0x70, 0x2c, 0xd9, 0x16, 0x74, 0x12, 0xa9, 0xc5, 0x18, 0x79, 0x83, 0x68, 0x88, 0xd0, 0x67,
	0x31, 0x46, 0xf6, 0x04, 0xba, 0x95, 0x5b, 0x2b, 0xaf, 0xc4, 0xc8, 0xf1, 0x39, 0x12, 0x2d, 0xa7,
	0x1e, 0x09, 0x65, 0x8f, 0xa1, 0x6b, 0xec, 0x30, 0xbf, 0x98, 0xe8, 0xc2, 0xab, 0xf8, 0x67, 0xcd,
	0x5e, 0xad, 0xdf, 0xcc, 0x96, 0x8c, 0x1d, 0x1e, 0x25, 0xf4, 0x58, 0xce, 0x34, 0x2c, 0x8d, 0x53,
	0x01, 0xe4, 0xf3, 0xb3, 0x0d, 0x4f, 0x12, 0xca, 0x5e, 0xc2, 0xbf, 0x49, 0x28, 0x85, 0xc7, 0xdc,
	0xe2, 0x50, 0x39, 0x8f, 0x16, 0x25, 0x5f, 0xe8, 0xd5, 0xfa, 0x8d, 0x6c, 0x3d, 0xb2, 0x03, 0xe1,
	0x31, 0x9b, 0x72, 0xec, 0x35, 0x6c, 0x24, 0x97, 0x9b, 0x9c, 0xbb, 0xc2, 0xaa, 0x92, 0x4e, 0x73,
	0xa1, 0xb4, 0x72, 0x97, 0xbc, 0x45, 0x4e, 0x1e, 0x15, 0xa7, 0x33, 0x82, 0x23, 0xe2, 0xd9, 0x36,
	0x2c, 0x26, 0x37, 0x8e, 0x85, 0x1a, 0xf1, 0x36, 0x9d, 0x2c, 0x45, 0xf4, 0x3e, 0x40, 0xec, 0x29,
	0xac, 0x24, 0x89, 0xc7, 0x11, 0x96, 0x97, 0x46, 0x23, 0x07, 0x92, 0xa5, 0x7b, 0x7d, 0xad, 0x60,
	0xf6, 0x10, 0x52, 0x92, 0xf9, 0x85, 0xb8, 0xe6, 0x1d, 0x12, 0xa5, 0x59, 0x1c, 0x89, 0x6b, 0xf6,
	0x08, 0xd2, 0x95, 0x73, 0x21, 0xa5, 0x45, 0xe7, 0xf8, 0x22, 0x49, 0x96, 0x22, 0x7a, 0x10, 0xc1,
	0x30, 0xa2, 0x42, 0x78, 0x1c, 0x1a, 0x7b, 0x13, 0x42, 0x5d, 0xa2, 0x50, 0xa1, 0x82, 0x8e, 0x25,
	0x7b, 0x05, 0xff, 0xa7, 0x3e, 0x63, 0xa1, 0x74, 0x7e, 0xa9, 0x2c, 0xca, 0xbc, 0x30, 0xe3, 0x52,
	0xe8, 0x1b, 0xbe, 0x4c, 0x2d, 0x53, 0x92, 0x9f, 0x84, 0xd2, 0x1f, 0x03, 0x7d, 0x18, 0x59, 0xf6,
	0x16, 0x36, 0x93, 0xb5, 0x30, 0xda, 0x5b, 0x51, 0x78, 0x63, 0x73, 0x89, 0xa5, 0xb0, 0x7e, 0x8c,
	0xda, 0xf3, 0x2e, 0xb9, 0x53, 0xa2, 0x87, 0x53, 0xc9, 0x60, 0xaa, 0x60, 0x2f, 0x60, 0xfd, 0x36,
	0xef, 0xdb, 0x26, 0x7c, 0x85, 0x9c, 0x6b, 0xd3, 0xa4, 0x6f, 0xa9, 0xd9, 0x17, 0x20, 0x9c, 0xfb,
	0x66, 0xac, 0xe4, 0xab, 0xbf, 0xbd, 0x80, 0x84, 0xb2, 0xfe, 0x34, 0x6a, 0xe5, 0x72, 0xa3, 0x47,
	0x4a, 0x23, 0x67, 0x74, 0xfd, 0xea, 0xf1, 0xb9, 0x2f, 0x84, 0x86, 0x37, 0xae, 0x5c, 0x2e, 0x0a,
	0xaf, 0xae, 0x90, 0xaf, 0x91, 0xa4, 0xa5, 0xdc, 0x01, 0xd5, 0x61, 0x0c, 0xca, 0xe5, 0x12, 0x47,
	0xe8, 0x51, 0xf2, 0x75, 0x62, 0xdb, 0xca, 0x0d, 0x22, 0xb0, 0xf3, 0xa3, 0x06, 0xad, 0x0c, 0x5d,
	0x69, 0xb4, 0x43, 0xc6, 0x61, 0xa1, 0xb0, 0x28, 0x82, 0x30, 0x6c, 0x50, 0x2b, 0xab, 0xca, 0xc0,
	0x4c, 0x4a, 0x49, 0x4c, 0x3d, 0x32, 0xa9, 0x0c, 0x4c, 0xd5, 0xbc, 0x11, 0x99, 0x54, 0xb2, 0x2d,
	0x98, 0x0b, 0xcb, 0x49, 0x1b, 0xd3, 0xd9, 0xeb, 0xec, 0xc6, 0xb5, 0x0d, 0x5b, 0x9a, 0x11, 0xc1,
	0xb6, 0x21, 0x6e, 0x2f, 0x6f, 0xf6, 0x1a, 0x7f, 0x2a, 0x22, 0xb3, 0xf7, 0xbd, 0x0e, 0x8b, 0xa1,
	0x76, 0xa7, 0x68, 0xaf, 0x54, 0x81, 0xec, 0x19, 0xc0, 0x21, 0x9d, 0x89, 0xb6, 0x7d, 0xd6, 0xb2,
	0xd1, 0x4d, 0x45, 0x75, 0x9d, 0x9d, 0x7f, 0x82, 0xfa, 0x8c, 0xce, 0x79, 0x5f, 0x75, 0x8c, 0xe5,
	0x5e, 0xea, 0x7d, 0x58, 0xfd, 0x80, 0x3e, 0xb0, 0xef, 0x6e, 0x4e, 0xe2, 0x40, 0x06, 0x77, 0x9a,
	0xde, 0xc0, 0xe6, 0x5f, 0xa6, 0x03, 0x2d, 0xa7, 0x43, 0xbf, 0xc3, 0x7f, 0x3e, 0x4f, 0x5f, 0xbd,
	0xfd, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xab, 0xfc, 0x22, 0x10, 0x05, 0x00, 0x00,
}
